
datafile: /Users/hattifattener/Documents/ias/mbii/modelling_paper/data/fits/real/2pt_ia_illustris_composite.fits
nbins : 8
rlim : [0.1,24.]
correlations : wgp wpp wgg
cosmology : illustris
box_size : 75.
kmin : 0.06
kmax : 5000
bias: 1.

redshifts : 0.0 

savedir : illustris/2pt/txt/
shapes : data/cats/fits/Illustris-1_${SNAPSHOT}_non-reduced_galaxy_shapes.fits
positions : data/cats/fits/Illustris-1_${SNAPSHOT}_non-reduced_galaxy_shapes.fits
snapshots : 135 114 98 85
#114 98 85
njk : 3

fits:
  output : 2pt_illustris.fits
  snapshots : 135 114 98 85
  correlations : wgp wpp wgg
  covariance : illustris/cov/covmat-analytic-iteration2.txt