
datafile: /home/ssamurof/hydro_ias/data/2pt/fits/2pt_mbii.fits
nbins : 12
rlim : [0.1,33]
correlations : wgp wpp wgg
cosmology : mbii
box_size : 100.
ng : 0.11356
sigma_e : 0.145
kmin : 0.06
kmax : 60
bias: 1.2
aia : 1.4

redshifts : 0.062 0.300 0.625 1.00

savedir : mbii/2pt/txt/
shapes : data/cats/fits/MBII_85_non-reduced_galaxy_shapes.fits
positions : data/cats/fits/MBII_85_non-reduced_galaxy_shapes.fits