
datafile: /home/ssamurof/mbii/datavecs/2pt_ia_mbii.fits
nbins : 10
rlim : [0.1,33]
correlations : wgg
cosmology : mbii
box_size : 100.
ng : 0.11356
sigma_e : 0.411
kmin : 0.06
kmax : 60
bias: 1.

redshifts : 0.062 0.300 0.625 1.00

savedir : mbii/2pt/txt/
shapes : data/cats/fits/MBII_85_non-reduced_galaxy_shapes.fits
positions : data/cats/fits/MBII_85_non-reduced_galaxy_shapes.fits