datafile: data/2pt/fits/2pt_tng.fits
nbins : 12
rlim : [0.1,68.]
correlations : wgp wpp wgg
cosmology : tng
box_size : 205.
ng : (0.02,0.0100) (0.02,0.0098) (0.019,0.0093) (0.017,0.008)
sigma_e : 0.136 0.144 0.1519 0.199
kmin : 0.06
kmax : 60
bias: 1.455445 1.565454 1.701701 1.953629
aia : 0.3685700 1.299420 0.9325798 1.970159 
wigner: True


redshifts : 0.0 0.3 0.625 1.

savedir : tng_low_stellar_mass/2pt/txt/
shapes : data/cats/fits/TNG300-1_${SNAPSHOT}_non-reduced_galaxy_shapes.fits
positions : data/cats/fits/TNG300-1_${SNAPSHOT}_non-reduced_galaxy_shapes.fits
njk : 4

snapshots : 99 78 62 50

split_type : all stellar_mass_low

fits:
  output : 2pt_tng.fits
  snapshots : 99 78 62 50
  correlations : wgp wpp wgg
  covariance : tng/cov/covmat-analytic.txt