
datafile: /home/ssamurof/mbii/datavecs/2pt_ia_mbii_compositecov.fits
nbins : 12
rlim : [0.1,68.]
correlations : wgp wpp wgg
cosmology : tng
box_size : 207.
ng : 0.02932091719004712
sigma_e : 0.21
kmin : 0.06
kmax : 5000
bias: 1.

redshifts : 0.0

savedir : tng/2pt/txt/
shapes : data/cats/fits/TNG300-1_${SNAPSHOT}_non-reduced_galaxy_shapes.fits
positions : data/cats/fits/TNG300-1_${SNAPSHOT}_non-reduced_galaxy_shapes.fits
njk : 4

snapshots : 99 78 62 50

split_type : central satellite

fits:
  output : 2pt_tng.fits
  snapshots : 99 78 62 50
  correlations : wgp wpp wgg
  covariance : tng/cov/covmat-analytic-iteration5.txt