
datafile: data/2pt/fits/2pt_tng.fits
nbins : 12
rlim : [0.1,68.]
correlations : wgp wpp wgg
cosmology : tng
box_size : 207.
ng :  (0.02,0.0066) (0.02,0.0063) (0.019,0.0055) (0.017,0.00450)
sigma_e : 0.1169 0.125 0.134 0.141
kmin : 0.06
kmax : 60
bias: 1.144857 1.286370 1.365146 1.582094
aia : 0.5752641 0.9595733 0.8757070 0.9030528
wigner: True

redshifts : 0.0 0.3 0.625 1.

savedir : tng_s/2pt/txt/
shapes : data/cats/fits/TNG300-1_${SNAPSHOT}_non-reduced_galaxy_shapes.fits
positions : data/cats/fits/TNG300-1_${SNAPSHOT}_non-reduced_galaxy_shapes.fits
njk : 4

snapshots : 99 78 62 50

split_type : all satellite

fits:
  output : 2pt_tng.fits
  snapshots : 99 78 62 50
  correlations : wgp wpp wgg
  covariance : tng_s/cov/tng-covmat-analytic.txt